name: Static Checks

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    paths:
      - '**.gd'
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - '**.gd'

jobs:
  linter-checks:
    name: 'Linter Checks'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Toolkit
      uses: Scony/godot-gdscript-toolkit@master
      
    - name: Linter
      run: gdlint ./
